name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r elementor-select2-taxonomies-control-artslab.zip . -x ".git/*" ".github/*"
    - name: Initial Zip
      run: echo "Created initial zip"
    - name: Zip the Zip
      run: zip -r elementor-select2-taxonomies-control-artslab2.zip ./elementor-select2-taxonomies-control-artslab.zip
    - name: First Zip Delete
      run: rm elementor-select2-taxonomies-control-artslab.zip
    - name: Zip Rename
      run: mv elementor-select2-taxonomies-control-artslab2.zip updates/elementor-select2-taxonomies-control-artslab.zip
    - name: Release activities
      run: rm updates/update.json
      run: cp updates/update-template.json updates/update.json
      run: sed -i 's/_VERSION_/3.0/' updates/update.json
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: voxsar