name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r elementor-select2-taxonomies-control-artslab.zip . -x ".git/*" ".github/*"
    - name: Initial Zip
      run: echo "Created initial zip"
    - name: Zip Zip
      run: zip -r elementor-select2-taxonomies-control-artslab.zip ./elementor-select2-taxonomies-control-artslab.zip
    - name: Nested Zip
      run: echo "Created initial release"
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: voxsar